# Generated by Django 4.2.1 on 2023-05-22 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(verbose_name="Описание изображения"),
                ),
                (
                    "neg_prompt",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Нежелательные характеристики",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="", verbose_name="Изображение"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сгенерированная картина",
                "verbose_name_plural": "Сгенерированные картины",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
